const leyendaAliasesGlobales = {
  3: "Comunas",
  Atacama: "Región de Atacama",
  REGION: "Límite Regional",
  PROVINCIA: "Límite Provincial",
  COMUNA: "Límite Comunal",
  OPERANDO: "En Operación",
  OPERACION: "En Operación",
  EN_CONSTRUCCION: "En Construcción",
  CONSTRUCCION: "En Construcción",
  PROYECTO: "En Proyecto",
  PLANIFICADO: "Planificado",
  CERRADO: "Cerrado/Inactivo",
  ABANDONO: "En Abandono",
  500: "500 kV (Alta Tensión)",
  220: "220 kV (Media-Alta Tensión)",
  110: "110 kV (Media Tensión)",
  23: "23 kV (Media-Baja Tensión)",
  "<=1 kV": "Menor o igual a 1 kV",
  ">1 kV y <15 kV": "Entre 1 kV y 15 kV",
  "15 kV": "15 kV (Media Tensión)",
  NULL: "Tensión no especificada",
  EOLICO: "Energía Eólica",
  FOTOVOLTAICO: "Energía Solar Fotovoltaica",
  TERMOELECTRICA: "Energía Termoeléctrica",
  "HIDRAULICA PASADA": "Energía Hidroeléctrica de Pasada",
  PERMANENTE: "Cauce Permanente",
  TEMPORAL: "Cauce Temporal",
  INTERMITENTE: "Cauce Intermitente",
  EMBALSE: "Embalse",
  LAGO: "Lago",
  LAGUNA: "Laguna",
  Asentamiento: "Localidad/Asentamiento",
  URBANO: "Área Urbana",
  RURAL: "Área Rural",
  AGRICOLA: "Uso Agrícola",
  FORESTAL: "Uso Forestal",
  MINERO: "Uso Minero",
  INDUSTRIAL: "Uso Industrial",
  RESIDENCIAL: "Uso Residencial",
  SI: "Sí",
  NO: "No",
  PUBLICO: "Público",
  PRIVADO: "Privado",
};

export default leyendaAliasesGlobales;
